# header
DROPDOWN_DAILY_STREAK = ('xpath', '//li[@data-component-name="DropdownDailyStreak"]')
START_FOR_FREE_BUTTON = ('xpath', '//button//span[normalize-space() = "Start for free"]')
SIGN_IN_BUTTON = ('xpath', '//button//span[normalize-space() = "Sign in"]')

# body
START_PROJECT_BUTTON = ('xpath', '//a[@click-event-target = "projects"]')
SELECT_COURSE_BUTTON = ('xpath', '//a[@click-event-target = "tracks"]')
PYTHON_BUTTON = ('xpath', '//a[@data-component-name="RouterLink"][text() = "Python"]')
JAVA_BUTTON = ('xpath', '//a[@data-component-name="RouterLink"][text() = "Java"]')
KOTLIN_BUTTON = ('xpath', '//a[@data-component-name="RouterLink"][text() = "Kotlin"]')
JAVASCRIPT_BUTTON = ('xpath', '//a[@data-component-name="RouterLink"][text() = "JavaScript"]')
GO_BUTTON = ('xpath', '//a[@data-component-name="RouterLink"][text() = "Go"]')
SCALA_BUTTON = ('xpath', '//a[@data-component-name="RouterLink"][text() = "Scala"]')
SHELL_BUTTON = ('xpath', '//a[@data-component-name="RouterLink"][text() = "Shell"]')
ZOOKEEPER_PROJECT_BUTTON = ('xpath', '//a[@aria-label="Zookeeper with Python"]')
ALL_COURSES_BUTTON = ('xpath', '//a[@click-event-target="category"][normalize-space() = "All courses"]')
TOP_COURSES_BUTTON = ('xpath', '//a[@click-event-target="category"][normalize-space() = "Top courses"]')
ANDROID_BUTTON = ('xpath', '//a[@click-event-target="category"][normalize-space() = "Android"]')
MATH_BUTTON = ('xpath', '//a[@click-event-target="category"][normalize-space() = "Math"]')
FRONTEND_BUTTON = ('xpath', '//a[@click-event-target="category"][normalize-space() = "Frontend"]')
BEGINNER_COURSES_BUTTON = ('xpath', '//a[@click-event-target="category"][normalize-space() = "Beginner-friendly"]')
LOAD_MORE_BUTTON = ('xpath', '//button[@data-component-name="Primitive"][normalize-space() = "Load more"]')
FIRST_COURSE_CARD = ('xpath', '(//div[@data-component-name="TrackCard"])[1]')
FIRST_COURSE_STATISTIC = ('xpath', '(//div[contains(@class,"track-statistics")])[1]')

# footer
FULL_CATALOG_BUTTON = ('xpath', '//footer//a[@click-event-target="full_catalog"]')
BIOINFORMATICS_BUTTON = ('xpath', '//footer//a[@click-event-target="Bioinformatics"]')
CAREERS_BUTTON = ('xpath', '//footer//a[@click-event-target = "careers"]')
HELP_CENTER_BUTTON = ('xpath', '//footer//a[@click-event-target = "help-center"]')
GOOGLE_PLAY_BUTTON = ('xpath', '//footer//a[@click-event-target="google-play"]')
APP_STORE_BUTTON = ('xpath', '//footer//a[@click-event-target="app-store"]')
YOUTUBE_BUTTON = ('xpath', '//footer//a[@aria-label="Hyperskill on YouTube"]')
REDDIT_BUTTON = ('xpath', '//footer//a[@title ="Hyperskill on Reddit"]')
